mutation {
  api1 : createApi(domain : "localhost"){
		createEndpoint(path : "/"){
      setMethod(method : "GET")
      modifyHeaders{
        setHeader(key : "content-type", value : "application/json") 
      }
    }    
  }
  api2 : createApi(domain : "google.com"){
		createEndpoint(path : "/"){
      setMethod(method : "GET")
      modifyHeaders{
        setHeader(key : "content-type", value : "application/json") 
      }
    }    
  }
}
