scalar JSON

type Query {
	apis:[Api]
	call(api : String!, argv : [String], filter : String) : JSON
}


type Api {
	name : String
	domain : String
	endpoints : [Endpoint]
}

type Endpoint {
	name : String
	path : String
	method : String
	description : String
	headers : [Header]
	responseHeaders : [Header]
	queryParams : [String]
}

type Header {
	key : String
	value : String 
}

type Mutation {
	modifyApi(name :String!) : ModifyApi
	createApi(name :String!) : ModifyApi
	deleteApi(name :String!) : String
}

type ModifyApi {
	setDomain( domain : String! ) : String
	createEndpoint(name : String!): ModifyEndpoint
	modifyEndpoint(name : String!): ModifyEndpoint
	deleteEndpoint(name : String!): String
}

type ModifyEndpoint {
	setPath(path:String!) : String
	setMethod(method:String!) : String
	setDescription(description: String!) : String 
	modifyHeaders : ModifyHeaders
	modifyResponceHeaders: ModifyHeaders
	modifyBody: ModifyBody
	modifyResponceBody : ModifyBody
	addQueryParam(params : [String]!): [String]
}

type ModifyHeaders {
	setHeader(key : String!, value : String!) : String
	deleteHeader(key : String!) : String
}

type ModifyBody {
	empty: String
}

